import = [
	"~/.config/alacritty/themes/themes/gruvbox_dark.toml"
]

shell = "/bin/zsh"

[font]
normal = { family = "FiraCode Nerd Font Mono", style = "Regular" }
bold = { family = "FiraCode Nerd Font Mono", style = "Bold" }
italic = { family = "FiraCode Nerd Font Mono", style = "Italic" }
size = 10
